[workspace]
members = [ "crates/gamedon_bits", "crates/gamedon_bus", "crates/gamedon_cpu", "crates/gamedon_debugger", "crates/gamedon_disassembler", "crates/gamedon_file", "crates/gamedon_lexer", "crates/gamedon_opcode", "crates/gamedon_ppu", "crates/gamedon_graphics", "crates/gamedon"]
resolver = "2"

[workspace.dependencies]
bitflags = "2.9.1"
clap = { version = "4.5.41", features = ["derive"] }
color-eyre = "0.6.5"
glyphon = "0.10.0"
owo-colors = { version = "4.2.2", features = ["supports-colors"] }
pollster = "0.4.0"
rustyline = "16.0.0"
thiserror = "2.0.12"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
wgpu = "28.0.0"
winit = "0.30.12"
zerocopy = "0.8.31"
zerocopy-derive = "0.8.31"

gamedon_bits = { path = "crates/gamedon_bits" }
gamedon_bus = { path = "crates/gamedon_bus" }
gamedon_cpu = { path = "crates/gamedon_cpu" }
gamedon_file = { path = "crates/gamedon_file" }
gamedon_graphics = { path = "crates/gamedon_graphics" }
gamedon_lexer = { path = "crates/gamedon_lexer" }
gamedon_opcode = { path = "crates/gamedon_opcode" }

[workspace.lints.rust]
unsafe_code = "warn"
unreachable_pub = "warn"
unexpected_cfgs = { level = "warn", check-cfg = [
    "cfg(fuzzing)",
    "cfg(codspeed)",
] }

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -2 }
# Allowed pedantic lints
char_lit_as_u8 = "allow"
collapsible_else_if = "allow"
collapsible_if = "allow"
implicit_hasher = "allow"
map_unwrap_or = "allow"
match_same_arms = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
module_name_repetitions = "allow"
must_use_candidate = "allow"
similar_names = "allow"
single_match_else = "allow"
too_many_lines = "allow"
needless_continue = "allow"       # An explicit continue can be more readable, especially if the alternative is an empty block.
unnecessary_debug_formatting = "allow"  # too many instances, the display also doesn't quote the path which is often desired in logs where we use them the most often.
# Without the hashes we run into a `rustfmt` bug in some snapshot tests, see #13250
needless_raw_string_hashes = "allow"
# Disallowed restriction lints
print_stdout = "warn"
print_stderr = "warn"
dbg_macro = "warn"
empty_drop = "warn"
empty_structs_with_brackets = "warn"
exit = "warn"
get_unwrap = "warn"
rc_buffer = "warn"
rc_mutex = "warn"
rest_pat_in_fully_bound_structs = "warn"
# nursery rules
redundant_clone = "warn"
debug_assert_with_mut_call = "warn"
unused_peekable = "warn"
missing_const_for_fn = "warn"

# Diagnostics are not actionable: Enable once https://github.com/rust-lang/rust-clippy/issues/13774 is resolved.
large_stack_arrays = "allow"
