[package]
name = "gamedon_debugger"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { workspace = true }
color-eyre = { workspace = true }
owo-colors = { workspace = true }
rustyline = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

gamedon_bus = { workspace = true }
gamedon_cpu = { workspace = true }
gamedon_file = { workspace = true }
gamedon_lexer = { workspace = true }

[lints]
workspace = true
